### ISSUE TITLE
Instead of service/<servicename> lets follow api/<resource> pattern

### ISSUE THREAD

**Issue by dibosh** [riyadhalnur/godi#1]
This is supposed to be used to scaffold a single service- and those are api resource endpoints.

**Comment by riyadhalnur** [comment]
The decision to host multiple services or one only depends on the end-user based on the use case. No reason why someone can't host multiple listeners under 1 repo if they choose to (in some cases it makes more sense than having multiple repos doing the same thing).

Placing a module under service is also mainly a suggestion in the README. The boilerplate doesn't enforce the resource naming path. As long as the services are mounted, they should work regardless.

**Comment by dibosh** [comment]
The point is monorepos are not easy to maintain and requires good expertise to have across. In terms of code maintenance, test coverage maintenance, unified pipeline etc. Which is why that's still not so popular and only practiced in orgs with advanced and matured tech practices. The purpose of this boilerplate should be targeting general and simple use cases- where people tend to stick towards single repo for single service. That should be how it is, and the option to make this work like a monorepo should be an advanced topic in the readme- showing it supports that. Does it make sense?

**Comment by riyadhalnur** [comment]
Not really. No one's arguing what's hard and what's not. The boilerplate does not enforce monorepo or a multi-repo setup nor does it state anywhere to use it as such. Do you mean to say I should add the resource naming scheme, as you mentioned above, as a way to structure code in the README?

**Comment by dibosh** [comment]
That can work.
