### ISSUE TITLE
Instead of each commonly used package having dedicated folder, can we move to common or core instead?

### ISSUE THREAD

**Issue by dibosh** [riyadhalnur/godi#2]
Instead of -

pkg
 - middleware
 - helpers
 - logger

can we -

pkg
 - core
    - helpers
    - middleware
    - logger

**Comment by riyadhalnur** [comment]
Too much nesting IMO when there are no go files in the `pkg` root. In real-life use case scenarios, if your reusing the packages under `pkg`, they should ideally be placed in a separate repo of its own anyways so that you can do `github.com/user/service-core/pkg/middleware` for example.
